name: 'Project "Piper"'
description: 'CI/CD tooling for the SAP Ecosystem'
inputs:
  command:
    description: 'command to run'
    required: true
    default: 'help'
  flags:
    description: 'flags/arguments for command'
    required: false
    default: ''
runs:
  using: 'node12'
  main: 'dist/index.js'
