name: CI

on: [push]

jobs:
  units:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - run: npm test

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run action to show Project Piper version
      uses: ./
      with:
        command: version
        flags: "-v"
